# -*- coding: utf-8 -*-
"""assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XSjXg0Ae3BuLyoplJi_13hYZ6wqUus3
"""

'''
Assignment 4

You will need the data. In a shell, download the data and extract to the base folder:

>> mkdir data
>> wget https://course.ccs.neu.edu/cs6120s26/data/twitter/en_US.twitter.txt -O data/en_US.twitter.txt
'''

import nltk
import utils
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.data.path.append('.')

class SpecialTokens:
    """
    Class of special tokens
    """
    def __init__(self, start_token = "<s>", end_token = "<e>", unknown_token = "<unk>"):
        self.start_token = start_token
        self.end_token = end_token
        self.unknown_token = unknown_token

class NGramModel():
    """
    This class holds your n-gram model and all its parameters, which include:

      - previous_n_gram: the last n-gram that appeared prior to the current one
      - n-gram_counts: a dictionary specifying the context words
    """
    def __init__(self, n_gram_counts,
               n_plus1_gram_counts, vocabulary, special_tokens, k=1):
        self.n_gram_counts = n_gram_counts
        self.n_plus1_gram_counts = n_plus1_gram_counts
        self.vocabulary = vocabulary
        self.special_tokens = special_tokens
        self.k = k

#@title Question 1

def preprocess_data(filename, count_threshold, special_tokens,
                    sample_delimiter='\n', split_ratio=0.8):
    """
    Ungraded: You do not need to change this function.

    Preprocess data, i.e.,
        - Find tokens that appear at least N times in the training data.
        - Replace tokens that appear less than N times by "<unk>" .
    Args:
        count_threshold: Words whose count is less than this are
                      treated as unknown.

    Returns:
        training_data = list of lists denoting tokenized sentence. This looks like
                        the following:

                        [ ["this", "<unk>", "example"],
                          ["another", "sentence", "<unk>", "right"],
                         ...
                        ]
        test_data = Same format as above.
        vocabulary = list of vocabulary words. This looks like the following:

                        ["vocab-word-1", "vocab-word-2", etc.]
    """

    # Create sentences and tokenize the data to create a list of strings.
    tokenized_data = read_and_tokenize_sentences(filename, sample_delimiter)

    # Create the training / test splits
    train_size = int(len(tokenized_data) * split_ratio)
    train_data = tokenized_data[0:train_size]
    test_data = tokenized_data[train_size:]

    # Get the closed vocabulary using the train data
    vocabulary = get_words_with_nplus_frequency(train_data, count_threshold)

    # For the train data, replace less common words with unknown token
    train_data_replaced = replace_oov_words_by_unk(
        train_data, vocabulary, unknown_token = special_tokens.unknown_token)

    # For the test data, replace less common words with "<unk>"
    test_data_replaced = replace_oov_words_by_unk(
        test_data, vocabulary, unknown_token = special_tokens.unknown_token)

    return train_data_replaced, test_data_replaced, vocabulary

def preprocess_data_test():
    """
    Ungraded: You can use this function to test out preprocess_data.
    """
    tmp_train = "the sky is blue.\nleaves are green.\nsmell all the roses."
    tmp_test = "roses are red."

    with open('tmp_data.txt', 'w') as f:
      f.write(str(tmp_train) + '\n')
      f.write(str(tmp_test) + '\n')

    special_tokens = SpecialTokens()
    count_threshold = 1

    tmp_train_repl, tmp_test_repl, tmp_vocab = preprocess_data(
        "tmp_data.txt", count_threshold, special_tokens, split_ratio = 0.75)

    assert tmp_test_repl == [['roses', 'are', '<unk>', '.']] or \
      tmp_test_repl == [[special_tokens.start_token,
                         'roses', 'are', '<unk>',
                         special_tokens.end_token]] or \
      tmp_test_repl == [[special_tokens.start_token,
                         'roses', 'are', '<unk>', '.',
                         special_tokens.end_token]], \
      print("tmp_test_repl is not correct")

    assert tmp_train_repl == [['the', 'sky', 'is', 'blue', '.'],
                              ['leaves', 'are', 'green', '.'],
                              ['smell', 'all', 'the', 'roses', '.']] or \
           tmp_train_repl == [[special_tokens.start_token,
                               'the', 'sky', 'is', 'blue',
                               special_tokens.end_token],
                              [special_tokens.start_token,
                               'leaves', 'are', 'green',
                               special_tokens.end_token],
                              [special_tokens.start_token,
                               'smell', 'all', 'the', 'roses',
                               special_tokens.end_token]] or \
           tmp_train_repl == [[special_tokens.start_token,
                               'the', 'sky', 'is', 'blue', '.',
                               special_tokens.end_token],
                              [special_tokens.start_token,
                               'leaves', 'are', 'green', '.',
                               special_tokens.end_token],
                              [special_tokens.start_token,
                               'smell', 'all', 'the', 'roses', '.',
                               special_tokens.end_token]], \
      print("tmp_train_repl is not correct")

    print("\033[92m Successful test")

    return

#@title Q1.1 Read / Tokenize Data from Sentences

from typing import dataclass_transform
def read_and_tokenize_sentences(filename, sample_delimiter="\n"):
    """
    Args:
        - filename = (e.g., "en_US.twitter.txt")
        - sample_delimiter = delimits each sample (i.e., each tweet)

    Example usage:
       $ read_and_tokenize_sentences(sentences)

       [['sky', 'is', 'blue', '.'],
        ['leaves', 'are', 'green'],
        ['roses', 'are', 'red', '.']]A

    You can use nltk's tokenize function here.

       nltk.word_tokenize(sentence)
    """

    tokenized_sentences = []
    # read doc
    with open(filename, 'r', encoding='utf-8') as f:
      data = f.read()
    #split doc into sentences
    sentences = data.split(sample_delimiter)

    #scan each sentence
    for sentence in sentences:
      sentence = sentence.strip()
      if sentence:
        tokens = nltk.word_tokenize(sentence)
        tokens = [token.lower() for token in tokens]
        tokenized_sentences.append(tokens)

    return tokenized_sentences

def get_words_with_nplus_frequency(train_data, count_threshold):

    vocabulary = []
    word_counts = {}

    for sentence in train_data:
      for word in sentence:
        if word not in word_counts:
          word_counts[word] = 1
        else:
          word_counts[word] += 1

    for word, count in word_counts.items():
      if count >= count_threshold:
        vocabulary.append(word)

    return vocabulary

#@title Q1.2 Replace OOV Words with Special Token

def replace_oov_words_by_unk(data, vocabulary, unknown_token="<unk>"):

    vocabulary = set(vocabulary)
    replaced_data = []

    for sentence in data:
      replaced_sentence = []

      for word in sentence:
          if word in vocabulary:
            replaced_sentence.append(word)
          else:
            replaced_sentence.append(unknown_token)
      replaced_data.append(replaced_sentence)

    return replaced_data

#@title Q2 Count N-Grams

def count_n_grams(data, n, special_tokens):
    """
    Count all n-grams in the data

    Args:
        data: List of lists of words
        n: Number of words in a sequence
        special_tokens: A structure that contains:
          - start_token = "<s>"
          - end_token = "<e>"
          - unknown_token = "unk"

    Returns:
        A dictionary that maps a tuple of n-words to its frequency
    """

    # Initialize dictionary of n-grams and their counts
    n_grams = {}

    for sentence in data:
      #add start_token and end token
      tokenized_sentence = [special_tokens.start_token] * (n - 1) + sentence + [special_tokens.end_token]

      #using sliding window to to find n_grams
      for i in range(len(tokenized_sentence) - n + 1):
        n_gram = tuple(tokenized_sentence[i:i+n])
        if n_gram in n_grams:
          n_grams[n_gram] += 1
        else:
          n_grams[n_gram] = 1

    return n_grams

def count_n_grams_test():
    """
    Ungraded: You can use this function to test out count_n_grams.
    """
    tmp_data = "i like a cat\nthis dog is like a cat"
    with open('tmp_data.txt', 'w') as f:
      f.write(tmp_data + '\n')

    sentences, _, _ = preprocess_data(
        "tmp_data.txt", 0, SpecialTokens(), split_ratio = 1.0)

    received = count_n_grams(sentences, 2, SpecialTokens())
    expected = { ('<s>', 'i'): 1,
      ('i', 'like'): 1, ('like', 'a'): 2, ('a', 'cat'): 2, ('cat', '<e>'): 2,
      ('<s>', 'this'): 1, ('this', 'dog'): 1, ('dog', 'is'): 1, ('is', 'like'): 1}

    assert received == expected, print("Received: \n", received,
                                       "\n\nExpected: \n", expected)

    print("\033[92m Successful test")

    return

count_n_grams_test()

def make_probability_matrix(n_plus1_gram_counts, vocabulary, k):
    '''
    To use this function, you'll need to get a utils function:

      >> wget -nc https://course.ccs.neu.edu/cs6120s26/data/twitter/utils.py

    Then, you can visualize your probability matrices. For example, consider the following:

      sentences = [['i', 'like', 'a', 'cat'],
                       ['this', 'dog', 'is', 'like', 'a', 'cat']]
      unique_words = list(set(sentences[0] + sentences[1]))
      bigram_counts = count_n_grams(sentences, 2, SpecialTokens())
      print(make_probability_matrix(bigram_counts, unique_words, k=1))
    '''

    count_matrix = utils.make_count_matrix(n_plus1_gram_counts, vocabulary)
    count_matrix += k
    prob_matrix = count_matrix.div(count_matrix.sum(axis=1) + k*len(vocabulary), axis=0)

    return prob_matrix

sentences = [['i', 'like', 'a', 'cat'],
             ['this', 'dog', 'is', 'like', 'a', 'cat']]
unique_words = list(set(sentences[0] + sentences[1]))
bigram_counts = count_n_grams(sentences, 2, SpecialTokens())
print("bigram counts")
display(utils.make_count_matrix(bigram_counts, unique_words))
print("bigram probabilities")
display(make_probability_matrix(bigram_counts, unique_words, k=1))

#@title Q3 Estimate the Probabilities

def estimate_probabilities(context_tokens, ngram_model):
    """
    Estimate the probabilities of a next word using the n-gram counts with k-smoothing

    Args:
        word: next word
        previous_n_gram: A sequence of words of length n
        ngram_model: a structure that contains:
            - n_gram_counts: Dictionary of counts of n-grams
            - n_plus1_gram_counts: Dictionary of counts of (n+1)-grams
            - vocabulary_size: number of words
            - k: positive constant, smoothing parameter

    Returns:
        A dictionary mapping from next words to probability
    """
    probabilities = {}

    context_tuple = tuple(context_tokens)
    context_count = ngram_model.n_gram_counts.get(context_tuple, 0)

    possible_words = ngram_model.vocabulary + [ngram_model.special_tokens.end_token,
                                               ngram_model.special_tokens.unknown_token]
    V = len(possible_words)
    denominator = context_count + ngram_model.k * V

    for word in possible_words:

        n_plus1_gram = context_tuple + (word,)

        n_plus1_count = ngram_model.n_plus1_gram_counts.get(n_plus1_gram, 0)

        probability = (n_plus1_count + ngram_model.k) / denominator

        probabilities[word] = probability

    return probabilities

def estimate_probabilities_test():
    """
    Ungraded: You can use this function to test out estimate_probabilities.
    """

    tmp_data = "i like a cat\nthis dog is like a cat"
    with open('tmp_data.txt', 'w') as f:
      f.write(tmp_data + '\n')

    sentences, _, vocabulary = preprocess_data(
        "tmp_data.txt", 0, SpecialTokens(), split_ratio = 1.0)

    # unique_words = list(set(sentences[0] + sentences[1]))
    unigram_counts = count_n_grams(sentences, 1, SpecialTokens())
    bigram_counts = count_n_grams(sentences, 2, SpecialTokens())

    ngram_model = NGramModel(unigram_counts, bigram_counts, vocabulary,
                             SpecialTokens(), k=1)

    expected = {'i': 0.09090909090909091, 'like': 0.09090909090909091,
                'a': 0.09090909090909091, 'cat': 0.2727272727272727,
                'this': 0.09090909090909091, 'dog': 0.09090909090909091,
                'is': 0.09090909090909091, '<e>': 0.09090909090909091,
                '<unk>': 0.09090909090909091}

    assert estimate_probabilities(["a"], ngram_model) == expected, \
      print("estimate_probabilities is not correct")

    print("\033[92m Successful test")

estimate_probabilities_test()

#@title Q4 Inference

def predict_next_word(partial_sentence, ngram_model):
    """
    Predicts the next word in a partial sentence using the provided n-gram model.

    Args:
        partial_sentence: The partial sentence as a string.
        ngram_model: An instance of the NGramModel class.

    Returns:
        The predicted next word (string) or None if no prediction can be made.
    """

    # transfer words into lower
    tokens = nltk.word_tokenize(partial_sentence)
    tokens = [token.lower() for token in tokens]

    # replace unkown words as 'UNK'
    vocab_set = set(ngram_model.vocabulary)
    processed_tokens = []
    for word in tokens:
        if word in vocab_set:
            processed_tokens.append(word)
        else:
            processed_tokens.append(ngram_model.special_tokens.unknown_token)

    # determine the context length 'n' of the model
    n = 1
    for key in ngram_model.n_gram_counts.keys():
      n = len(key)
      break

    if len(processed_tokens) < n:
        #if the input sentence is too short
        num_padding_needed = n - len(processed_tokens)

        padding = []
        for i in range(num_padding_needed):
            padding.append(ngram_model.special_tokens.start_token)

        context_tokens = padding + processed_tokens
    else:
        # if the input sentence is long enough, just take the last n words
        context_tokens = processed_tokens[-n:]

    # estimate the probabilities of all possible next words
    probabilities = estimate_probabilities(context_tokens, ngram_model)

    # find the word with the maximum probability
    best_word = None
    max_prob = -1.0

    for word, prob in probabilities.items():
        if prob > max_prob:
            max_prob = prob
            best_word = word

    # return the most likely next word
    return best_word

#@title Q5 Extra Credit

#download data

!wget -nc https://course.ccs.neu.edu/cs6120s26/data/hemingway/hemingway-edit.txt -P data/
!wget -nc https://www.gutenberg.org/cache/epub/100/pg100.txt -P data/
!wget -nc https://www.gutenberg.org/cache/epub/12242/pg12242.txt -P data/

class StyleGram:

    def __init__(self, style_files):
        """
        We will only be passing style_files in. All your processing and
        training should be done by the time this function retunrs.
        """
        self.style_files = style_files
        self.models = []


        special_tokens = SpecialTokens()
        # filter out words that appear less than 2 times
        count_threshold = 2

        # Train a Bigram model for each author's file
        for file in style_files:
            # 1. Preprocess the data for the current file
            train_data_repl, _, vocabulary = preprocess_data(
                file, count_threshold, special_tokens, split_ratio=1.0
            )

            # 2. Count N-Grams (n=1 for unigrams, n=2 for bigrams)
            unigrams = count_n_grams(train_data_repl, 1, special_tokens)
            bigrams = count_n_grams(train_data_repl, 2, special_tokens)

            # 3. Create and store the NGramModel
            model = NGramModel(unigrams, bigrams, vocabulary, special_tokens, k=1.0)
            self.models.append(model)

        return

def write_in_style_ngram(self, passage):
        """
        Takes a passage in, matches it with a style, given a list of
        filenames, and predicts the next word that will appear
        using a bigram model.

        Args:
            passage: A string that contains a passage
            style_file: a list of filenames to be used to determine the style

        Returns:
             single word <string>
             probability associated with the word <float>
             index of "style" it originated from (e.g., 0 for 1st file) <int8>
             probability associated with the style <float>
        """

        # 1. Tokenize and transfer the input passage to lowercase
        tokens = nltk.word_tokenize(passage)
        lower_tokens = []
        for t in tokens:
            lower_tokens.append(t.lower())

        best_style_idx = -1
        best_style_log_prob = -float('inf')

        # 2. Style Classifier: Calculate the log probability of the passage for each model
        for idx, model in enumerate(self.models):
            log_prob_sum = 0.0
            vocab_set = set(model.vocabulary)

            # Handle OOV (Out of Vocabulary) words
            processed_tokens = []
            for w in lower_tokens:
                if w in vocab_set:
                    processed_tokens.append(w)
                else:
                    processed_tokens.append(model.special_tokens.unknown_token)

            # Pad with a start token to calculate bigram probabilities for the sequence
            eval_tokens = [model.special_tokens.start_token] + processed_tokens

            # Sum the log probabilities
            for i in range(len(eval_tokens) - 1):
                context = [eval_tokens[i]]
                target_word = eval_tokens[i+1]

                # Estimate probabilities based on the current context word
                probs = estimate_probabilities(context, model)

                # Get the probability of the target word; use a tiny value to prevent log(0)
                word_prob = probs.get(target_word, 1e-10)
                log_prob_sum += math.log(word_prob)

            # Update the best style if this model has a higher generation probability
            if log_prob_sum > best_style_log_prob:
                best_style_log_prob = log_prob_sum
                best_style_idx = idx

        # 3. Predict the next word using the winning style model
        winning_model = self.models[best_style_idx]
        vocab_set = set(winning_model.vocabulary)

        # Extract the last word of the passage as the context for the Bigram prediction
        if len(lower_tokens) > 0:
            last_word = lower_tokens[-1]
        else:
            last_word = winning_model.special_tokens.start_token

        # Check if the last word is in the winning model's vocabulary
        if last_word not in vocab_set:
            last_word = winning_model.special_tokens.unknown_token

        # Get the probability distribution for the next word
        next_word_probs = estimate_probabilities([last_word], winning_model)

        # Find the word with the highest probability
        word = None
        probability_word = -1.0

        for w, p in next_word_probs.items():
            if p > probability_word:
                probability_word = p
                word = w

        # Assign final return variables exactly as requested by the documentation
        style_file = best_style_idx
        probability_style = best_style_log_prob

        return word, probability_word, style_file, probability_style

# Example Usage
if __name__ == "__main__":
    # Create an instance of your NGramModel here, using your training data
    special_tokens = SpecialTokens()
    count_threshold = 10
    train_data_replaced, test_data_replaced, vocabulary = preprocess_data(
        "en_US.twitter.txt", count_threshold, special_tokens
    )

    preprocess_data_test()
    count_n_grams_test()
    estimate_probabilities_test()

    # n=2
    unigram_counts = count_n_grams(train_data_replaced, 1, special_tokens)
    bigram_counts = count_n_grams(train_data_replaced, 2, special_tokens)

    ngram_model = NGramModel(unigram_counts, bigram_counts, vocabulary,
                            special_tokens, k=1)

    partial_sentence = "i love"  # Example partial sentence
    predicted_word = predict_next_word(partial_sentence, ngram_model)
    print(f"The predicted next word for '{partial_sentence}' is: {predicted_word}")

